// <auto-generated />
using System;
using Br.Com.Company.CurrencyQuote.Data.Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Br.Com.Company.CurrencyQuote.Data.Infraestructure.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220114134620_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Br.Com.Company.CurrencyQuote.Data.Entities.SegmentRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("creation_date")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("rate");

                    b.Property<int>("Segment")
                        .HasColumnType("integer")
                        .HasColumnName("segment");

                    b.HasKey("Id")
                        .HasName("pk_segment_rate");

                    b.HasIndex("Segment")
                        .IsUnique()
                        .HasDatabaseName("ix_segment_rate_segment");

                    b.ToTable("segment_rate", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
